<?php
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * Usage: stever_body_class_get_meta( 'stever_body_class_text' )
 */

/* Metabox Easy Retrieval */
function stever_body_class_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}
/* Metabox Add */
function stever_body_class_add_meta_box() {
	add_meta_box(
		'stever_body_class-stever-body-class',
		__( 'Body Class', 'stever_body_class' ),
		'stever_body_class_html',
		array( 'page', 'post', ),
		'side',
		'high'
	);
}
add_action( 'add_meta_boxes', 'stever_body_class_add_meta_box' );

/* Metabox HTML */
function stever_body_class_html( $post) {
	wp_nonce_field( '_stever_body_class_nonce', 'stever_body_class_nonce' ); ?>
	<textarea name="stever_body_class_text" id="stever_body_class_text"><?php echo stever_body_class_get_meta( 'stever_body_class_text' ); ?></textarea>
<?php
}

/* Metabox Save */
function stever_body_class_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['stever_body_class_nonce'] ) || ! wp_verify_nonce( $_POST['stever_body_class_nonce'], '_stever_body_class_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['stever_body_class_text'] ) )
		update_post_meta( $post_id, 'stever_body_class_text', esc_attr( $_POST['stever_body_class_text'] ) );
}
add_action( 'save_post', 'stever_body_class_save' );



/* Add Body Class from Metabox  */
function stever_body_class( $classes ) {
	$add_classes = stever_body_class_get_meta( 'stever_body_class_text' );
	if( !empty( $add_classes ) && $classes ){
		/* Transform to lowercase, remove duplicates */
		$add_classes_separate = explode( ' ', strtolower( $add_classes ) );
		return array_merge( $classes, array_unique( $add_classes_separate ) );
	}
	return $classes;
}
add_filter( 'body_class', 'stever_body_class' );


function stever_admin_body_class( $classes ) {
	$screen = get_current_screen();

	if( 'page' == $screen->post_type ){
		$add_classes = stever_body_class_get_meta( 'stever_body_class_text' );
		if( !empty( $add_classes ) ){

			$classes .= $add_classes;
		}
		return $classes;
	}
}
add_filter( 'admin_body_class', 'stever_admin_body_class' );