<?php
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * Usage: stever_body_class_get_meta( 'stever_body_class_text' )
 */

/* Metabox Easy Retrieval */
function stever_body_class_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( $field && ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}
/* Metabox Add */
function stever_body_class_add_meta_box() {
	add_meta_box(
		'stever_body_class-stever-body-class',
		__( 'Body Class', 'stever_body_class' ),
		'stever_body_class_html',
		array( 'page', 'post', ),
		'side',
		'high'
	);
}
add_action( 'add_meta_boxes', 'stever_body_class_add_meta_box' );

/* Metabox HTML */
function stever_body_class_html( $post) {
	wp_nonce_field( '_stever_body_class_nonce', 'stever_body_class_nonce' ); ?>
	<textarea name="stever_body_class_text" id="stever_body_class_text"><?php echo stever_body_class_get_meta( 'stever_body_class_text' ); ?></textarea>
<?php
}

/* Metabox Save */
function stever_body_class_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['stever_body_class_nonce'] ) || ! wp_verify_nonce( $_POST['stever_body_class_nonce'], '_stever_body_class_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['stever_body_class_text'] ) )
		update_post_meta( $post_id, 'stever_body_class_text', esc_attr( $_POST['stever_body_class_text'] ) );
}
add_action( 'save_post', 'stever_body_class_save' );



/* Add Body Class */
function stever_body_class( $classes ) {

	/* Add from Post Cat */
	if( 'post' == get_post_type() ){
		$post_cats = get_the_terms( get_the_id(), 'category' );
		
		foreach( $post_cats as $post_cat ){
			$post_slug = $post_cat->slug;
			if( 'uncategorized' !== $post_slug ){
				$classes[] = 'cat-' . $post_slug;
				$classes = array_unique( $classes );
			}
		}
	}

	/* Add from Metabox  */
	$add_classes = stever_body_class_get_meta( 'stever_body_class_text' );
	if( !empty( $add_classes ) && $classes ){
		/* Transform to lowercase, remove duplicates */
		$add_classes_separate = explode( ' ', strtolower( $add_classes ) );
		$classes = array_unique( array_merge( $classes, $add_classes_separate) );
	}
	return $classes;
}
add_filter( 'body_class', 'stever_body_class' );


function stever_admin_body_class( $classes ) {
	$screen = get_current_screen();

	if( 'page' == $screen->id ){
		$add_classes = stever_body_class_get_meta( 'stever_body_class_text' );
		if( !empty( $add_classes ) ){
			$classes .= $add_classes;
		}
		return $classes;
	}
}
add_filter( 'admin_body_class', 'stever_admin_body_class' );



/* Adds body class to block editor iframe.
 * See: `/js/editor.js`
 * @via: https://wordpress.stackexchange.com/a/427560
 */

function site_editor_styles() {
	$screen = get_current_screen();

	if ('page' == $screen->id) {
		$add_classes = stever_body_class_get_meta('stever_body_class_text');
		if (!empty($add_classes)) {
			$classes .= $add_classes;
		}
		// Enqueue or Javascript
		wp_enqueue_script(
			'sr-block-iframe-classes',
			get_template_directory_uri() . '/js/editor.js',
			array('wp-blocks', 'wp-dom'),
			filemtime(get_stylesheet_directory() . '/js/editor.js'),
			true
		);

		// Pass the class names to the script
		wp_localize_script('sr-block-iframe-classes', 'iframeBodyData', [
			'classes' => $classes,
		]);		
	}
}
add_action('enqueue_block_assets', 'site_editor_styles');